package models

import (
	"time"

	"gorm.io/gorm"
)

type POStatus string

const (
	POStatusDraft     POStatus = "draft"
	POStatusPending   POStatus = "pending"
	POStatusApproved  POStatus = "approved"
	POStatusSent      POStatus = "sent"
	POStatusReceived  POStatus = "received"
	POStatusCancelled POStatus = "cancelled"
)

type PurchaseOrder struct {
	ID                  string              `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	SupplierID          string              `gorm:"type:uuid;not null" json:"supplier_id"`
	Supplier            Supplier            `gorm:"constraint:OnDelete:RESTRICT" json:"supplier,omitempty"`
	DestinationLocationID string            `gorm:"type:uuid;not null" json:"destination_location_id"`
	DestinationLocation Location            `gorm:"constraint:OnDelete:RESTRICT" json:"destination_location,omitempty"`
	Status              POStatus            `gorm:"type:po_status;default:draft" json:"status"`
	ExpectedDate        *time.Time          `json:"expected_date,omitempty"`
	Notes               *string             `json:"notes,omitempty"`
	AutoGenerated       bool                `gorm:"default:false" json:"auto_generated"`
	Items               []PurchaseOrderItem `gorm:"foreignKey:PurchaseOrderID" json:"items,omitempty"`
	CreatedBy           string              `gorm:"type:uuid;not null" json:"created_by"`
	UpdatedBy           *string             `gorm:"type:uuid" json:"updated_by,omitempty"`
	CreatedAt           time.Time           `json:"created_at"`
	UpdatedAt           time.Time           `json:"updated_at"`
	DeletedAt           gorm.DeletedAt      `gorm:"index" json:"deleted_at,omitempty"`
}

type PurchaseOrderItem struct {
	ID              string        `gorm:"type:uuid;default:gen_random_uuid();primaryKey" json:"id"`
	PurchaseOrderID string        `gorm:"type:uuid;not null" json:"purchase_order_id"`
	ProductID       string        `gorm:"type:uuid;not null" json:"product_id"`
	Product         Product       `gorm:"constraint:OnDelete:RESTRICT" json:"product,omitempty"`
	Quantity        float64       `gorm:"type:numeric(15,3);not null" json:"quantity"`
	UnitCost        float64       `gorm:"type:numeric(15,2);not null" json:"unit_cost"`
	Total           float64       `gorm:"type:numeric(15,2);-:all" json:"total"`
	CreatedAt       time.Time     `json:"created_at"`
}
