package services

import (
	"log"
	"time"

	"github.com/hugoquesada/invex/internal/models"
	"gorm.io/gorm"
)

type AutoPOService struct {
	db *gorm.DB
}

func NewAutoPOService(db *gorm.DB) *AutoPOService {
	return &AutoPOService{db: db}
}

func (s *AutoPOService) GeneratePurchaseOrders() {
	var lowStock []struct {
		models.Inventory
		ProductName string
		SupplierID  *string
	}

	query := `
		SELECT i.*, p.name as product_name, p.primary_supplier_id as supplier_id
		FROM inventory i
		JOIN products p ON p.id = i.product_id
		WHERE i.quantity <= p.reorder_point
		AND p.active = true
		AND p.primary_supplier_id IS NOT NULL
	`

	if err := s.db.Raw(query).Scan(&lowStock).Error; err != nil {
		log.Printf("AutoPO: failed to query low stock: %v", err)
		return
	}

	for _, item := range lowStock {
		if item.SupplierID == nil {
			continue
		}

		orderQty := item.Product.MaxStock - item.Quantity
		if orderQty <= 0 {
			orderQty = item.Product.ReorderPoint * 2
		}

		po := models.PurchaseOrder{
			SupplierID:            *item.SupplierID,
			DestinationLocationID: item.LocationID,
			Status:                models.POStatusPending,
			AutoGenerated:         true,
			ExpectedDate:          ptrTime(time.Now().AddDate(0, 0, 7)),
			Notes:                 ptrString("Auto-generated from reorder point"),
		}

		if err := s.db.Create(&po).Error; err != nil {
			log.Printf("AutoPO: failed to create PO: %v", err)
			continue
		}

		poItem := models.PurchaseOrderItem{
			PurchaseOrderID: po.ID,
			ProductID:       item.ProductID,
			Quantity:        orderQty,
			UnitCost:        item.Product.UnitCost,
		}

		if err := s.db.Create(&poItem).Error; err != nil {
			log.Printf("AutoPO: failed to create PO item: %v", err)
		}

		log.Printf("AutoPO: generated PO %s for product %s, qty: %.3f", po.ID, item.ProductName, orderQty)
	}
}

func ptrTime(t time.Time) *time.Time {
	return &t
}

func ptrString(s string) *string {
	return &s
}
